-- name: Goal has no done_when
-- class: Definition
-- metric: done_when_coverage
-- action: add a done_when line to the goal's frontmatter
-- severity: WARN
-- guardrail: BARE-ABSENCE SEMANTICS, INHERITED FROM #102, NOT DECIDED HERE (Design decision 4, .sdlc/plans/118.md) -- fact_goal.done_when_present is computed by insight/ingest/artifact_reader.py's goal_record as "done_when" in fm, presence of the key, never truthiness of its value; insight/tests/test_artifact_reader.py:72-86's own test_goal_missing_done_when_is_recorded_as_absent_not_defaulted and test_goal_with_empty_done_when_is_present_not_absent already pin both halves of this distinction (a goal with no done_when: line at all -> False; done_when: "" -> True, PRESENT-but-empty) -- this rule reads off that already-settled #102 semantic, it does not reopen it. ABSENCE-OR-EMPTY IS NOT BUILT -- fact_goal never stores the done_when TEXT anywhere, only the presence boolean, so a done_when: "" goal is indistinguishable at this rule's own grain from a genuinely filled-in one; closing that gap needs a new ingested column and writer, out of this story's scope. POPULATION: SELECT count(*) FROM fact_goal -- same denominator as coverage_verify_no_command.sql, DuckDB's own count(*) aggregate form, always exactly one row. THE SPEC'S :527 VERIFY-COMMAND CLAUSE IS MET BY REFERENCE, NOT DUPLICATED HERE -- insight/gaps/coverage_verify_no_command.sql (#117) already implements exactly that condition, in loop.py's own precedence; see that rule's own guardrail and .sdlc/plans/118.md Design decision 1. THE README CONTAMINATION THIS RULE WOULD OTHERWISE HAVE SURFACED ON ITS FIRST REAL RUN IS FIXED UPSTREAM -- insight/ingest/artifact_reader.py's discover_goal_files now excludes the sdlc-init-scaffolded README.md by exact filename (.sdlc/plans/118.md Design decision 2), so a future reader does not wonder why no README-named finding ever appears here. NO "MATCH BY GITHUB ISSUE NUMBER" ALTERNATIVE EXISTS OR IS NEEDED FOR THIS RULE -- fact_goal.issue has ZERO writers anywhere under insight/ingest/ today (the same exclusion class as fact_goal.pr, cited by coverage_review_missing.sql's own guardrail), so no live join from a goal row back to a GitHub issue number exists to match against; this rule reads done_when_present directly, no join needed. A REPO RUNNING discovery.source: github HAS ITS ACTIVE GOALS AS ISSUES THAT NEVER GET A fact_goal ROW AT ALL -- a discovery.source == "github" goal lives as a GitHub issue with no frontmatter text, out of scope for artifact_reader.py's frontmatter reader (#102 Design decision E); this rule, like discover_goal_files itself, measures LOCAL-MODE goals only -- a pre-existing scope limit from #102, disclosed here, not hidden.
-- population: SELECT count(*) FROM fact_goal
SELECT project_id, goal_id
FROM fact_goal
WHERE done_when_present = false
ORDER BY project_id, goal_id
