-- name: Goal has no plan artifact
-- class: Definition
-- metric: plan_artifact_coverage
-- action: add a plan file for the goal under .sdlc/plans/<goal-stem>.md, matching the local .sdlc/goals/ stem -- or, if this project's plans are named by a different convention (e.g. GitHub issue number), confirm that convention deliberately diverges from plan_artifact_present's own check
-- severity: WARN
-- guardrail: THE EXACT NAMING-CONVENTION MISMATCH, DISCLOSED PLAINLY (Design decision 3, .sdlc/plans/118.md) -- plan_artifact_present (insight/ingest/artifact_reader.py's goal_record) checks .sdlc/plans/<goal-stem>.md EXACTLY, matching the file it was read from by filename stem; a github-discovery repo whose plans are named by issue number (this repo's own real .sdlc/plans/94.md...117.md, verified live in this story's plan review: 0 of 19 real-and-README goal rows had plan_artifact_present = true before the README fix) will see EVERY local goal flagged by this rule -- a true statement about this repo's own directory-naming convention, not a bug in the check. TASK 3'S "NO FALSE POSITIVE ON A COMPLETE GOAL" CASE IS THEREFORE DEMONSTRATED ON A SYNTHETIC FIXTURE, NEVER REAL DATA, FOR EXACTLY THIS REASON -- stated directly, not left implicit; see insight/tests/test_gaps_definition_no_false_positive.py. POPULATION: SELECT count(*) FROM fact_goal -- same denominator as the sibling rule and coverage_verify_no_command.sql. THE SPEC'S :527 VERIFY-COMMAND CLAUSE IS MET BY REFERENCE, NOT DUPLICATED HERE -- insight/gaps/coverage_verify_no_command.sql (#117) already implements exactly that condition; see that rule's own guardrail and .sdlc/plans/118.md Design decision 1. NO "MATCH BY GITHUB ISSUE NUMBER" ALTERNATIVE EXISTS OR IS NEEDED -- fact_goal.issue has ZERO writers anywhere under insight/ingest/ today (the same exclusion class as fact_goal.pr, cited by coverage_review_missing.sql's own guardrail), so no live join from a goal row to a GitHub issue number exists that could be used to compute plan_artifact_present by issue number instead of by stem; that is a real, separate ingest-layer scope, not attempted here. A REPO RUNNING discovery.source: github HAS ITS ACTIVE GOALS AS ISSUES THAT NEVER GET A fact_goal ROW AT ALL -- a discovery.source == "github" goal has no frontmatter text, out of scope for artifact_reader.py's frontmatter reader (#102 Design decision E); this rule, like discover_goal_files itself, measures LOCAL-MODE goals only -- a pre-existing scope limit from #102, disclosed here, not hidden. IS NOT TRUE, NOT `= false` (post-PR-review nit): SQL equality is three-valued, so a NULL plan_artifact_present would fall out of `= false` entirely and the rule would render PASS -- population > 0, zero evidence rows -- for a goal nobody actually measured, which is the 'unmeasured reads as fine' collapse spec:534 forbids and this very class exists to catch. The column is NOT NULLable through any path today (it is in fact_goal's original CREATE TABLE, never added by a later ALTER, and _GOAL_UPSERT_SQL always supplies an explicit bool on both INSERT and the ON CONFLICT UPDATE), so this changes nothing now; it is what keeps the answer honest the day a second writer of fact_goal appears.
-- population: SELECT count(*) FROM fact_goal
SELECT project_id, goal_id
FROM fact_goal
WHERE plan_artifact_present IS NOT TRUE
ORDER BY project_id, goal_id
