// SPDX-License-Identifier: BUSL-1.1 - LoopSmith Insight. NOT MIT. See insight/LICENSE.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Cold-start-safe liveness probe (Decision 1, .sdlc/plans/299.md): HTTP 200 in all
         *     three store states -- the API PROCESS is genuinely healthy in every one of them (it
         *     started, it can reach the filesystem, it can respond); a missing or empty store is an
         *     expected pre-ingest state, not an outage.
         *
         *     CONTRACT, binding on every caller (plan-review amendment 4 -- this is the ABSENT-is-
         *     never-PASS doctrine, spec §3, applied one HTTP layer up from where E16.S2's Metric union
         *     will eventually enforce it in Pydantic): the body's `store` field
         *     ("missing" | "empty" | "populated") is what carries the real signal. A caller MUST branch
         *     on `store` and MUST NEVER read HTTP 200 alone as "healthy with data" -- collapsing all
         *     three into a single `{"status": "ok"}` (or reading 200 as implying data is present) is
         *     exactly the fake-healthy shape spec §3 opens with (the literal `0` shipped for "goals
         *     landed" against an empty store). See insight/api/README.md for the full contract.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Every catalog entry, resolved (spec §3's Metric union, issue #300 [E16.S2]): a cold or
         *     missing store degrades every metric to an absent state, never a crash and never a
         *     fabricated value -- the same read-connection, same try/except FileNotFoundError shape
         *     as /health above, reused rather than duplicated. `response_model=list[Metric]` is what
         *     makes FastAPI enforce the union's `extra="forbid"` on the way OUT, not merely in Python:
         *     a `MeasuredMetric`/absent-model mismatch here would fail serialization, not silently
         *     leak an extra field onto the wire.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbsentNoDataMetric
         * @description The metric's SQL exists (or ran) and returned nothing to measure -- a missing view, a
         *     view with zero rows, or a row whose value is NULL are all this same shape (see
         *     insight/api/metrics.py's `resolve_metric`, and `insight.dash.panel`'s `_metric_state`/
         *     `_scalar`, whose absence conventions this ports). Time, not a code change, fixes this.
         */
        AbsentNoDataMetric: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            /** Reliabilityclass */
            reliabilityClass: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "absent_no_data";
        };
        /**
         * AbsentUnbuiltMetric
         * @description There is no way to produce this metric yet -- no `.sql` file, or (this story's own scope-
         *     down, Decision (b)) a `.sql` file with no registered value/coverage extractor. Only a code
         *     change fixes this, never the passage of time.
         */
        AbsentUnbuiltMetric: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            /** Reliabilityclass */
            reliabilityClass: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "absent_unbuilt";
        };
        /**
         * Coverage
         * @description The numerator/denominator a `measured` metric's value was computed over -- e.g. "3/4
         *     landed without intervention" for autonomy rate. Never present on an absent metric: there is
         *     no coverage to report for a value that was never computed.
         */
        Coverage: {
            /** Denominator */
            denominator: number;
            /** Numerator */
            numerator: number;
        };
        /** MeasuredMetric */
        MeasuredMetric: {
            coverage: components["schemas"]["Coverage"];
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Reliabilityclass */
            reliabilityClass: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "measured";
            /** Unit */
            unit?: ("seconds" | "ratio" | "count") | null;
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["MeasuredMetric"] | components["schemas"]["AbsentNoDataMetric"] | components["schemas"]["AbsentUnbuiltMetric"])[];
                };
            };
        };
    };
}
